baseURL = 'https://side-realms.dev/'
relativeurls = true
publishDir = "docs"
languageCode = 'ja-jp'
theme = "m10c"
title = "お茶は綾鷹派"
buildDrafts = false
buildFuture = false
buildExpired = false
cleanDestinationDir = true
disableHugoGeneratorInject = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "log"
    name = "life log"
    url = "/log"
    weight = 2
  [[menu.main]]
    identifier = "tech"
    name = "tech"
    url = "/tech/"
    weight = 3
  [[menu.main]]
    identifier = "other"
    name = "other"
    url = "/other/"
    weight = 4
  [[menu.main]]
    identifier = "Portfolio"
    name = "Portfolio"
    url = "/portfolio/"
    weight = 5

[params]
  author = "KoheiDoi"
  description = "最近は颯も好き"
  memo = "内容の正確性は保証していません🐶"
  #menu_item_separator = " 🍙 "
  menu_item_separator = ""
  avatar = "images/avatar.jpg"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com"
#  [[params.social]]
#    icon = "twitter"
#    name = "Twitter"
#    url = "https://twitter.com"

[params.style]
darkestColor = "#121110"  # header background
darkColor = "#0d0c0b"     # page background
lightColor = "#d4cfc7"    # body text
lightestColor = "#f4f0e8" # title text
primaryColor = "#ff5c38"  # accent

[pagination]
pagerSize = 20

[markup.goldmark.renderer]
unsafe = true
